name: Api Vulkan Guide Rust - CI Information
on:
  push:
    branches:
      - main
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.1
      - name: Try Build
        run: cargo build --manifest-path api-vulkan-guide-rust/source-main/Cargo.toml
