name: Information Source Code Build Result
on:
  push:
    branches:
      - main
jobs:
  try-build-api-vulkan-tutorial-rust-2022:
    name: Try Build Api Vulkan Tutorial Rust 2022
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.64.0
      - name: Try Build
        run: cargo build --manifest-path api-vulkan-tutorial-rust-2022/Cargo.toml

  try-build-api-vulkan-guide-rust:
    name: Try Build Api Vulkan Guide
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.80.1
      - name: Try Build
        run: cargo build --manifest-path api-vulkan-guide-rust/source-main/Cargo.toml